### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by emilyanncr** [rndinfosecguy/OSWA-Experience-And-Exam-Preparation#1]
I just failed my first attempt at certification.  Can you provide any additional insight that may be able to help someone like me?  Thanks.

**Comment by rndinfosecguy** [comment]
Sorry, I am a bit late to the party here. Practice is the key. So I added some HTB machines which help in getting practice.
Beside this do whatever web related box you can spot. For example doing a lot easy boxes on HTB is definitely not a mistake. Hope your second try went well.
